name: Django-app workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    # для клонирования репозитория
    - uses: actions/checkout@v2

    - name: Set up Python
      # для развёртывания окружения Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r requirements.txt

    - name: Test with flake8 and django tests
      run: |
        python -m flake8
        cd infra_project
        python manage.py test


  build_and_push_to_dockerhub:
    name: Push docker image to DockerHub
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Check the repo
      uses: actions/checkout@v2

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Login DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: cokasqq/infra-actions:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_dockerhub
    steps:
    - name: executing remotee ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          sudo docker pull cokasqq/infra-actions
          sudo docker stop $(sudo docker ps -a -q)
          sudo docker run --rm -d -p 5000:5000 cokasqq/infra-actions


  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: ${{ github.workflow }} выполнен успешно.
